name: Deploy to S3

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::074460675775:role/GitHubActionsS3DeployRole
          aws-region: us-east-1  # replace with your region

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://<github-action-s3-bucket-web> --delete
        env:
          AWS_DEFAULT_REGION: us-east-1
