name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials from IAM Role
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<074460675775>:role/<GitHubActionsS3DeployRole>
          aws-region: us-east-1  # replace with your region

      - name: Sync files to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.github-action-s3-bucket-web }}
          SOURCE_DIR: 'website'   # optional: defaults to entire repository
