name: Assume AWS Role

on:
  push:
    branches:
      - main

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Assume Role
      run: |
        ROLE_ARN="arn:aws:iam::074460675775:role/GitHubActionsS3DeployRole123"
        CREDENTIALS=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name GitHubActionsSession --duration-seconds 900)
        
        if [ $? -ne 0 ]; then
          echo "Error: Failed to assume role $ROLE_ARN"
          echo "Command output: $CREDENTIALS"
          exit 1
        fi

        AWS_ACCESS_KEY_ID=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
        AWS_SECRET_ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
        AWS_SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')

        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
          echo "Error: Failed to retrieve temporary credentials."
          exit 1
        fi

        echo "::set-output name=AWS_ACCESS_KEY_ID::$AWS_ACCESS_KEY_ID"
        echo "::set-output name=AWS_SECRET_ACCESS_KEY::$AWS_SECRET_ACCESS_KEY"
        echo "::set-output name=AWS_SESSION_TOKEN::$AWS_SESSION_TOKEN"

      env:
        ROLE_ARN: "arn:aws:iam::074460675775:role/GitHubActionsS3DeployRole123"
name: Assume AWS Role

on:
  push:
    branches:
      - main

jobs:
  assume-role:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Assume Role
      run: |
        ROLE_ARN="arn:aws:iam::074460675775:role/GitHubActionsS3DeployRole123"
        CREDENTIALS=$(aws sts assume-role --role-arn "$ROLE_ARN" --role-session-name GitHubActionsSession --duration-seconds 900)
        
        if [ $? -ne 0 ]; then
          echo "Error: Failed to assume role $ROLE_ARN"
          echo "Command output: $CREDENTIALS"
          exit 1
        fi

        AWS_ACCESS_KEY_ID=$(echo "$CREDENTIALS" | jq -r '.Credentials.AccessKeyId')
        AWS_SECRET_ACCESS_KEY=$(echo "$CREDENTIALS" | jq -r '.Credentials.SecretAccessKey')
        AWS_SESSION_TOKEN=$(echo "$CREDENTIALS" | jq -r '.Credentials.SessionToken')

        if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ] || [ -z "$AWS_SESSION_TOKEN" ]; then
          echo "Error: Failed to retrieve temporary credentials."
          exit 1
        fi

        echo "::set-output name=AWS_ACCESS_KEY_ID::$AWS_ACCESS_KEY_ID"
        echo "::set-output name=AWS_SECRET_ACCESS_KEY::$AWS_SECRET_ACCESS_KEY"
        echo "::set-output name=AWS_SESSION_TOKEN::$AWS_SESSION_TOKEN"

      env:
        ROLE_ARN: "arn:aws:iam::074460675775:role/GitHubActionsS3DeployRole123"
